version: 2.1

commands:
  build:
    steps:
      - checkout
      - run:
          name: update
          command: apt update
      - run:
          name: install java
          command: apt install default-jdk -y
      - run:
          name: install php
          command: apt install php-fpm -y
      - run:
          name: Install system packages
          command: apt-get update && apt-get -y install zip git zlib1g-dev wget
      - run:
          name: Install PHP extensions
          command: |
            apt-get install pdo-mysql          
            apt-get install libcurl4-gnutls-dev          
            pecl install xdebug            
      - run:
          name: Display PHP information
          command: |
            php -v
      - run:
          name: Check PHP sintax
          command: find . -name \*.php -exec php -l "{}" \;
      - run:
          name: Download composer
          command: |
            php -r "copy('http://getcomposer.org/installer', 'composer-setup.php');"
            php composer-setup.php
      - run:
          name: Mock hook-git
          command: mkdir -p .git/hooks
      - run:
          name: Install dependecy-composer
          command: php composer.phar install
      - run:
          name: Run PHPUnit
          command: |
            ./cc-test-reporter before-build
            vendor/bin/phpunit --coverage-clover clover.xml
      - persist_to_workspace:
          root: /
          paths:
            - app
  
  buildjava:
    steps:
    - checkout
    - run:
        name: Java Check
        command: java -version
    - run:
        name: check list
        command: ls

jobs:
  build-php56:
    working_directory: /app
    docker:
      - image: php:5.6-apache
        environment:
          APP_ENV: test
    steps:
      - build

  build-php72:
    working_directory: /app
    docker:
      - image: ubuntu      
        environment:
          APP_ENV: test
    steps:
      - build

  build-java:
    working_directory: /app
    docker:
      - image: openjdk:8-alpine
        environment:
          APP_ENV: test
    steps:
      - buildjava

workflows:
  build_publish_deploy:
    jobs:
      - build-php56
      - build-php72
      - build-java:
            requires:
                - build-php72 
